# Numpy
Numerical Python, или, кратко, "Numpy" - это основополагающий пакет, на котором построены многие из наиболее распространённых пакетов Data Science. Numpy предоставляет нам высокоэффективные многомерные массивы, которые мы можем использовать в качестве векторов или матриц.

Ключевые особенности:
* ndarrays: n-мерный список однотипных данных, которые работают быстро и эффективно Существует ряд встроенных методов для ndarrays, позволяющих быстро обрабатывать данные без использования циклов (например, вычислить среднее значение).
* Транслирование: инструмент, который определяет явное поведение между многомерными массивами разных размеров.
* Векторизация: включает числовые операции над ndarrays.
* Ввод / вывод: упрощает чтение и запись данных из / в файл.

<p style="font-family: Arial; font-size:2.75em;color:purple; font-style:bold"><br>

Приступим к массивам<br><br></p>

**ndarrays** это эффективные по использованию памяти и времени многомерные массивы.

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Как создать одномерный numpy:
</p>

In [1]:
import numpy as np

an_array = np.array([3, 33, 333])  # создаём одномерный массив

print(type(an_array))              # Его тип: "<class 'numpy.ndarray'>"

<class 'numpy.ndarray'>


In [2]:
# Посмотрим на форму только что созданного массива, у него должно бытьлишь одно измерение (Rank 1)
print(an_array.shape)

(3,)


In [3]:
# т.к. это одномерный массив, нам достаточно обращаться к элементу по одному индексу
print(an_array[0], an_array[1], an_array[2]) 

3 33 333


In [4]:
an_array[0] =888            # ndarrays изменяемы

print(an_array)

[888  33 333]


<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Как создать двумерный массив:</p>

Обратите внимание на формат [ [row] , [row] ].  Двумерные массивы подходят для представления матриц, котороый часто используются в Data Science.

In [5]:
another = np.array([[11,12,13],[21,22,23]])   # Создаём двумерный массив

print(another)  # вывод

print("Форма - 2 ряда, 3 столбца: ", another.shape)  # ряды x столбцы                   

print("Элементы с индексами [0,0], [0,1], и [1,0] массива ndarray: ", another[0, 0], ", ",another[0, 1],", ", another[1, 0])

[[11 12 13]
 [21 22 23]]
Форма - 2 ряда, 3 столбца:  (2, 3)
Элементы с индексами [0,0], [0,1], и [1,0] массива ndarray:  11 ,  12 ,  21


<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Есть несколько способов создавать эти массивы:
</p>

Тут мы создадим несколько массивов с разными формами и различными наполняющими значениями. В Numpy есть несколько встроенных методов, которые помогут нам быстро и легко создавать массивы.

In [6]:
import numpy as np

# создаём матрицу 2х2, заполненную нулями
ex1 = np.zeros((2,2))      
print(ex1)                              

[[0. 0.]
 [0. 0.]]


In [7]:
# создаём матрицу 2х2, заполненную 9.0
ex2 = np.full((2,2), 9.0)  
print(ex2)

[[9. 9.]
 [9. 9.]]


In [8]:
# создаём матрицу 2х2, где на главной диагонали стоят единицы
ex3 = np.eye(2,2)
print(ex3)  

[[1. 0.]
 [0. 1.]]


Среди параметров функции ```eye``` есть k, отвечающий за смещение диагонали единиц на k вверх, если k \> 0, иначе на k вниз.

In [9]:
print(np.eye(3, 3))
print()
print(np.eye(3, 4))
print()
print(np.eye(3, 4, 2))
print()
print(np.eye(3, 4, -2))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]

[[0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 0. 0. 0.]]


In [10]:
# создаём массив единиц
ex4 = np.ones((1,2))
print(ex4)    

[[1. 1.]]


In [11]:
# Заметим, что ndarray  сверху (ex4) является двумерным, это 1х2 массив
print(ex4.shape)

# это значит, что нужно использовать два индекса для доступа к элементам
print()
print(ex4[0,1])

(1, 2)

1.0


In [12]:
# создание массива, наполненного дробными числами от 0 до 1
ex5 = np.random.random((2,2))
print(ex5)    

[[0.70297575 0.78991325]
 [0.71475597 0.13460234]]


<p style="font-family: Arial; font-size:2.75em;color:purple; font-style:bold"><br>

Индексация массива
<br><br></p>

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>
Срезы:
</p>

Так же, как мы использовали срезы со списками и строками, мы можем "срезать" индексирование, чтобы достать "подрегион", "подобласть" массива.

In [13]:
import numpy as np

# Двумерный массив с формой (3, 4)
an_array = np.array([[11,12,13,14], [21,22,23,24], [31,32,33,34]])
print(an_array)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


Воспользуемся срезами, чтобы получить подмассив содержащий первые 2 ряда х 2 колонки

In [14]:
an_array = np.array([[11,12,13,14], [21,22,23,24], [31,32,33,34]])
a_slice = an_array[:2, 1:3]
print(a_slice)

[[12 13]
 [22 23]]


Когда вы изменяете срез, вы также изменяете и "надмассив"(из которого получили срез)

In [15]:
an_array = np.array([[11,12,13,14], [21,22,23,24], [31,32,33,34]])
print("До:", an_array[0, 1])
a_slice = an_array[:2, 1:3]
a_slice[0, 0] = 1000    # a_slice[0, 0] тот же самый элемент, что и an_array[0, 1]
print("После:", an_array[0, 1])    

До: 12
После: 1000


<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Используем вместе индексы & срезы
</p>

Мы можем использовать комбинацию индексов и срезов чтобы создавать матрицы разных форм.

In [16]:
# создадим двумерный массив формы (3, 4)
an_array = np.array([[11,12,13,14], [21,22,23,24], [31,32,33,34]])
print(an_array)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


In [17]:
# примененяя вместе индексы & срезы, мы создаём массив меньшей размерности
row_rank1 = an_array[1, :]    # Одно измерение

print(row_rank1, row_rank1.shape)  # Заметьте только одни []

[21 22 23 24] (4,)


In [18]:
# Только срезы: создают массив той же самой размерности, что и an_array
row_rank2 = an_array[1:2, :]  # Два измерения

print(row_rank2, row_rank2.shape)   # Заметьте [[ ]]

[[21 22 23 24]] (1, 4)


In [19]:
# можно делать тоже самое с колонками массива:

print()
col_rank1 = an_array[:, 1]
col_rank2 = an_array[:, 1:2]

print(col_rank1, col_rank1.shape)  # Rank 1
print()
print(col_rank2, col_rank2.shape)  # Rank 2


[12 22 32] (3,)

[[12]
 [22]
 [32]] (3, 1)


<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Массив индексов для изменения элементов:
</p>

Иногда удобнее использовать массив индексов для доступа к элементам.

In [20]:
# Создаём новый массив
an_array = np.array([[11,12,13], [21,22,23], [31,32,33], [41,42,43]])

print('Начальный массив:')
print(an_array)

Начальный массив:
[[11 12 13]
 [21 22 23]
 [31 32 33]
 [41 42 43]]


In [21]:
# Создаём массив индексов
col_indices = np.array([0, 1, 2, 0])
print('\nВыбранные индексы столбцов : ', col_indices)

row_indices = np.arange(4)
print('\nВыбранные индексы рядов : ', row_indices)


Выбранные индексы столбцов :  [0 1 2 0]

Выбранные индексы рядов :  [0 1 2 3]


In [22]:
# Посмотрим на пары row_indices and col_indices. Это элементы, которые мы в дальнейшем поменяем.
for row,col in zip(row_indices,col_indices):
    print(row, ", ",col)

0 ,  0
1 ,  1
2 ,  2
3 ,  0


In [23]:
# Выберем по одному элементу из каждого ряда
print('Значения в массиве с этими индексами: ',an_array[row_indices, col_indices])

Значения в массиве с этими индексами:  [11 22 33 41]


In [24]:
# Изменим элементы в каждом ряду, используя полученные ранее индексы
an_array[row_indices, col_indices] += 100000

print('\nИзменённый массив:')
print(an_array)


Изменённый массив:
[[100011     12     13]
 [    21 100022     23]
 [    31     32 100033]
 [100041     42     43]]


<p style="font-family: Arial; font-size:2.75em;color:purple; font-style:bold"><br>
Boolean Indexing

<br><br></p>
<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Массив индексов для изменения элементов:
</p>

In [25]:
# создадим массив 3x2 
an_array = np.array([[11,12], [21, 22], [31, 32]])
print(an_array)

[[11 12]
 [21 22]
 [31 32]]


In [26]:
# создадим фильтр с булевскими значениями для каждого элемента (результатами применения условия к каждому элементу)
filter = (an_array > 15)
filter

array([[False, False],
       [ True,  True],
       [ True,  True]])

Заметьте, что фильтр того же размера, что и ```an_array```, заполнен ```True``` для элементов, удовлетворивших условию \> 15 и ```False``` для элемнтов меньших 15.

In [27]:
# теперь мы можем выбрать те элементы, которые удовлетворяют условию
print(an_array[filter])

[21 22 31 32]


In [28]:
# Ещё короче, можно не создавать епременную-фильтр просто написав

an_array[(an_array % 2 == 0)]

array([12, 22, 32])

Мы можем менять значения в массиве, подходящих под условие логического фильтра. Добавим всем чётным значениям 100.

In [29]:
an_array[an_array % 2 == 0] +=100
print(an_array)

[[ 11 112]
 [ 21 122]
 [ 31 132]]


<p style="font-family: Arial; font-size:2.75em;color:purple; font-style:bold"><br>

Типы данных и операции с массивами
<br><br></p>
<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Типы данных:
</p>

In [30]:
ex1 = np.array([11, 12]) # Python назначает тип данных
print(ex1.dtype)

int64


In [31]:
ex2 = np.array([11.0, 12.0]) # Python назначает тип данных
print(ex2.dtype)

float64


In [32]:
ex3 = np.array([11, 21], dtype=np.int64) #Вы сами можете сказать Python тип данных
print(ex3.dtype)

int64


In [33]:
# Вы можете это использовать, чтобы намеренно дробные привести к целым (используется функция floor)
ex4 = np.array([11.1,12.7], dtype=np.int64)
print(ex4.dtype)
print()
print(ex4)

int64

[11 12]


In [34]:
# Вы можете использовать это для приведения целых к дробным, если предвидите,
# что значения могут использоваться как дробные позже
ex5 = np.array([11, 21], dtype=np.float64)
print(ex5.dtype)
print()
print(ex5)

float64

[11. 21.]


<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Арифметические операции с массивами:

</p>

In [35]:
x = np.array([[111,112],[121,122]], dtype=np.int)
y = np.array([[211.1,212.1],[221.1,222.1]], dtype=np.float64)

print(x)
print()
print(y)

[[111 112]
 [121 122]]

[[211.1 212.1]
 [221.1 222.1]]


In [36]:
# сложение
print(x + y)         # Знак плюс работает
print()
print(np.add(x, y))  # как и numpy функция "add"

[[322.1 324.1]
 [342.1 344.1]]

[[322.1 324.1]
 [342.1 344.1]]


In [37]:
# вычитание
print(x - y)
print()
print(np.subtract(x, y))

[[-100.1 -100.1]
 [-100.1 -100.1]]

[[-100.1 -100.1]
 [-100.1 -100.1]]


In [38]:
# умножение
print(x * y)
print()
print(np.multiply(x, y))

[[23432.1 23755.2]
 [26753.1 27096.2]]

[[23432.1 23755.2]
 [26753.1 27096.2]]


In [39]:
# деление
print(x / y)
print()
print(np.divide(x, y))

[[0.52581715 0.52805281]
 [0.54726368 0.54930212]]

[[0.52581715 0.52805281]
 [0.54726368 0.54930212]]


In [40]:
# извлечение квадратного корня
print(np.sqrt(x))

[[10.53565375 10.58300524]
 [11.         11.04536102]]


In [41]:
# Экспоненцирование (e ** x)
print(np.exp(x))

[[1.60948707e+48 4.37503945e+48]
 [3.54513118e+52 9.63666567e+52]]


<p style="font-family: Arial; font-size:2.75em;color:purple; font-style:bold"><br>

Статистические методы, сортировка, и <br> <br> Операции со множествами:
<br><br>
</p>

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Базовые статистические операции:
</p>

In [42]:
# построим матрицу 2х5 рандомных чисел
arr = 10 * np.random.randn(2,5)
print(arr)

[[ -4.65776239 -11.904952    -3.72696771  12.6211718    9.50799439]
 [ 13.27505954  -0.48464577  -8.48287575 -20.80703432   4.74707178]]


In [43]:
# посчитаем среднее значение для всех элементов
print(arr.mean())

-0.9912940422946797


In [44]:
# посчитаем среднее значение по рядам
print(arr.mean(axis = 1))

[ 0.36789682 -2.3504849 ]


In [45]:
# посчитаем среднее значение по столбцам
print(arr.mean(axis = 0))

[ 4.30864858 -6.19479888 -6.10492173 -4.09293126  7.12753308]


In [46]:
# сумма всех элементов
print(arr.sum())

-9.912940422946797


In [47]:
# рассчёт медиан
print(np.median(arr, axis = 1))

[-3.72696771 -0.48464577]


<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Сортировка:
</p>

In [48]:
# создадим десятиэлементный массив рандомных чисел
unsorted = np.random.randn(10)

print(unsorted)

[-0.20806396 -0.12425655 -0.28915121  0.53115563 -0.9970193  -0.49913892
 -0.31325713  0.29096121  0.54699609 -1.21256979]


In [49]:
# создадим копию и отсортируем
sorted = np.array(unsorted)
sorted.sort()

print(sorted)
print()
print(unsorted)

[-1.21256979 -0.9970193  -0.49913892 -0.31325713 -0.28915121 -0.20806396
 -0.12425655  0.29096121  0.53115563  0.54699609]

[-0.20806396 -0.12425655 -0.28915121  0.53115563 -0.9970193  -0.49913892
 -0.31325713  0.29096121  0.54699609 -1.21256979]


In [50]:
# Сортировка на месте
unsorted.sort() 

print(unsorted)

[-1.21256979 -0.9970193  -0.49913892 -0.31325713 -0.28915121 -0.20806396
 -0.12425655  0.29096121  0.53115563  0.54699609]


<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Поиск уникальных элементов:
</p>

In [51]:
array = np.array([1,2,1,4,2,1,4,2])

print(np.unique(array))

[1 2 4]


<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Операции со множествами:
</p>

In [52]:
s1 = np.array(['стол','стул','лампочка'])
s2 = np.array(['лампа','лампочка','стул'])
print(s1, s2)

['стол' 'стул' 'лампочка'] ['лампа' 'лампочка' 'стул']


In [53]:
print( np.intersect1d(s1, s2) ) #пересечение по первому измерению

['лампочка' 'стул']


In [54]:
print( np.union1d(s1, s2) )

['лампа' 'лампочка' 'стол' 'стул']


In [55]:
print( np.setdiff1d(s1, s2) )# элементы в s1, которые не в s2

['стол']


In [56]:
print( np.in1d(s1, s2) )# какие элементы из s1 также в s2

[False  True  True]


<p style="font-family: Arial; font-size:2.75em;color:purple; font-style:bold"><br>

Транслирование:
<br><br>
</p>

Введение в транслирование. <br>

Операция транслирования - расширение одного или обоих массивов операндов до массивов с равной размерностью.

Детали можно посмотреть тут: <br>
https://docs.scipy.org/doc/numpy-1.10.1/user/basics.broadcasting.html

In [57]:
import numpy as np

start = np.zeros((4,3))
print(start)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [58]:
# создадим одномерный массив с 3 значениями
add_rows = np.array([1, 0, 2])
print(add_rows)

[1 0 2]


In [59]:
y = start + add_rows  # добавим к каждому ряду start используя транслирование
print(y)

[[1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]]


In [60]:
# создадим ndarray 4 x 1 для транслирования через столбцы
add_cols = np.array([[0,1,2,3]])
add_cols = add_cols.T #транспонируем

print(add_cols)

[[0]
 [1]
 [2]
 [3]]


In [61]:
# прибавиим к каждому столбцу of 'start'
y = start + add_cols 
print(y)

[[0. 0. 0.]
 [1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]]


In [62]:
# тут транслирование будет в оба измерения
add_scalar = np.array([1])  
print(start+add_scalar)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


Примеры:

In [63]:
# Создадим нашу матрицу 3х4
arrA = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arrA)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [64]:
# Создадим 4x1 массив
arrB = [0,1,0,2]
print(arrB)

[0, 1, 0, 2]


In [65]:
# Сложим их через транслирование
print(arrA + arrB)

[[ 1  3  3  6]
 [ 5  7  7 10]
 [ 9 11 11 14]]


<p style="font-family: Arial; font-size:2.75em;color:purple; font-style:bold"><br>

Тест скорости: ndarrays vs списки
<br><br>
</p>

Для начала установим параметры для теста.

In [66]:
from numpy import arange
from timeit import Timer

size    = 1000000
timeits = 1000

In [67]:
# создадим ndarray со значениями 0,1,2...,size-1
nd_array = arange(size)
print( type(nd_array) )

<class 'numpy.ndarray'>


In [68]:
# таймер ждёт операцию как параметр, 
# передадим nd_array.sum()
timer_numpy = Timer("nd_array.sum()", "from __main__ import nd_array")

print("Время numpy ndarray: %f секунд" % 
      (timer_numpy.timeit(timeits)/timeits))

Время numpy ndarray: 0.000575 секунд


In [69]:
# cоздадим лист со значеними 0,1,2...,size-1
a_list = list(range(size))
print (type(a_list) )

<class 'list'>


In [70]:
# таймер ждёт операцию как параметр, передадим sum(a_list)
timer_list = Timer("sum(a_list)", "from __main__ import a_list")

print("Время листа:  %f секнду" % 
      (timer_list.timeit(timeits)/timeits))

Время листа:  0.006011 секнду


<p style="font-family: Arial; font-size:2.75em;color:purple; font-style:bold"><br>

Чтение или запись на диск:
<br><br>
</p>
<p style="font-family: Arial; font-size:1.3em;color:#2462C0; font-style:bold"><br>

Двоичный формат:</p>

In [71]:
x = np.array([ 23.23, 24.24] )

In [72]:
np.save('an_array', x) #сохранение

In [73]:
np.load('an_array.npy')#чтение

array([23.23, 24.24])

<p style="font-family: Arial; font-size:1.3em;color:#2462C0; font-style:bold"><br>

Текстовый формат:</p>

In [74]:
np.savetxt('array.txt', X=x, delimiter=',')

In [75]:
np.loadtxt('array.txt', delimiter=',')

array([23.23, 24.24])

<p style="font-family: Arial; font-size:2.75em;color:purple; font-style:bold"><br>

Дополнительные операции над массивами
<br><br></p>

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Произведение матриц и скалярное произведение на векторах:

</p>

In [76]:
# посчитаем произведение двух матриц
x2d = np.array([[1,1],[1,1]])
y2d = np.array([[2,2],[2,2]])

print(x2d.dot(y2d))
print()
print(np.dot(x2d, y2d))

[[4 4]
 [4 4]]

[[4 4]
 [4 4]]


In [77]:
# посчитаем скалярное произведение двух векторов
a1d = np.array([9 , 9 ])
b1d = np.array([10, 10])

print(a1d.dot(b1d))
print()
print(np.dot(a1d, b1d))

180

180


In [78]:
# посчитаем матричное произведение матрицы на вектор
print(x2d.dot(a1d))
print()
print(np.dot(x2d, a1d))

[18 18]

[18 18]


<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Сумма:
</p>

In [79]:
# сумма элементов в массиве
ex1 = np.array([[11,12],[21,22]])

print(np.sum(ex1))          # сложить все элементы

66


In [80]:
print(np.sum(ex1, axis=0))  # сумма по столбцам

[32 34]


In [81]:
print(np.sum(ex1, axis=1))  # сумма по рядам

[23 43]


<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Поэлементные функции: </p>

Например, сравним два массива значений и найдём максимум из каждого.

In [82]:
x = np.random.randn(8)
x

array([-0.04914102, -0.1377977 , -0.81286848,  0.10503716, -0.27440468,
       -0.08386297,  0.0170102 , -0.60187463])

In [83]:
y = np.random.randn(8)
y

array([-0.30792413,  1.46022464,  0.29639181,  0.88452188, -0.13930537,
       -0.74544705, -0.18917284,  0.73704108])

In [84]:
# Возвращает поэлементный максимум между двумя массивами
# [max(x1, y1), max(x2, y2)...]
np.maximum(x, y)

array([-0.04914102,  1.46022464,  0.29639181,  0.88452188, -0.13930537,
       -0.08386297,  0.0170102 ,  0.73704108])

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Изменение формы массива:
</p>

In [85]:
# получаем значения от 0 до 19 в массив
arr = np.arange(20)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [86]:
# изменяем форму, чтобы получилась матрица 4х5
arr.reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Транспонирование:

</p>

In [87]:
# транспонируем
ex1 = np.array([[11,12],[21,22]])

ex1.T

array([[11, 21],
       [12, 22]])

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Индексирование с использованием where():</p>

In [88]:
x_1 = np.array([1,2,3,4,5])

y_1 = np.array([11,22,33,44,55])

filter = np.array([True, False, True, False, True])

In [89]:
out = np.where(filter, x_1, y_1) # если True, то x_1, иначе y_1
print(out)

[ 1 22  3 44  5]


In [90]:
mat = np.random.rand(5,5)
mat

array([[0.31408066, 0.98511899, 0.08991693, 0.21835733, 0.60519646],
       [0.03022016, 0.92861761, 0.01790191, 0.95008466, 0.09633713],
       [0.52985084, 0.39258024, 0.95492086, 0.92160903, 0.06012123],
       [0.01547259, 0.68575143, 0.70330308, 0.18961381, 0.5027586 ],
       [0.55958702, 0.78735455, 0.22899766, 0.86907146, 0.2302973 ]])

In [91]:
np.where( mat > 0.5, 1000, -1)# если True, то изменить на 1000, иначе на -1

array([[  -1, 1000,   -1,   -1, 1000],
       [  -1, 1000,   -1, 1000,   -1],
       [1000,   -1, 1000, 1000,   -1],
       [  -1, 1000, 1000,   -1, 1000],
       [1000, 1000,   -1, 1000,   -1]])

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Условия "any" или "all":</p> 

In [92]:
arr_bools = np.array([ True, False, True, True, False ])

In [93]:
arr_bools.any() # если есть хотя бы один True, то True

True

In [94]:
arr_bools.all() # если все элементы True, то True

False

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Генерация случайных чисел:
</p>

In [95]:
Y = np.random.normal(size = (1,5))[0] #рандомные значения из нормального (Гаусса) распределения
print(Y)

[-0.0780864   1.21982428  1.62495241  0.97503908 -1.09021255]


In [96]:
Z = np.random.randint(low=2,high=50,size=4) # значение между low и high, размер массива - 4
print(Z)

[21 13 46 30]


In [97]:
np.random.permutation(Z) #возвращает новую перестановку элементов в Z

array([30, 21, 46, 13])

In [98]:
np.random.uniform(size=4) #непрерывное равномерное распределение

array([0.88099047, 0.61535443, 0.00937248, 0.61614588])

In [99]:
np.random.normal(size=4)

array([-0.52092487, -1.88571432, -0.58874822, -1.9846877 ])

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Объединение данных:
</p>

In [100]:
K = np.random.randint(low=2,high=50,size=(2,2))
print(K)

print()
M = np.random.randint(low=2,high=50,size=(2,2))
print(M)

[[49 30]
 [ 7 33]]

[[30 47]
 [36 26]]


In [101]:
np.vstack((K,M)) #вертикальное объединение

array([[49, 30],
       [ 7, 33],
       [30, 47],
       [36, 26]])

In [102]:
np.hstack((K,M)) #горизонтальное объединение

array([[49, 30, 30, 47],
       [ 7, 33, 36, 26]])

In [103]:
np.concatenate([K, M], axis = 0) #сложение по столбцам

array([[49, 30],
       [ 7, 33],
       [30, 47],
       [36, 26]])

In [104]:
np.concatenate([K, M.T], axis = 1) #сложение по рядам

array([[49, 30, 30, 36],
       [ 7, 33, 47, 26]])